#!/usr/bin/env python3
"""Generates plugin/include/ForgePact/SkillTimerNames.hpp from hs-game-sdk.

Issue #55 follow-up (D-S4): the rule-based coverage tier resolves a talent's
cast object by NAME CONVENTION rather than a hand-typed table (AGENTS.md,
"Never Call an Address You Resolved by Hand") - every class-prefixed
hs-game-sdk object, keyed by its own name with the class prefix and trailing
`_obj` stripped, underscores removed, lower-cased
(`White_Mage_Healing_Zone_obj` -> `healingzone`). A companion object (anything
under `Player_Sentry_Parent_obj` in its ancestor chain - turrets, totems,
hydra, owner 2026-09-21) is dropped entirely, and a key more than one such
object would share is dropped too (ambiguous - never guessed at).

`--check` regenerates the table in memory and diffs it against the file on
disk without writing anything, so CI (and a human) can tell the checked-in
header is what this generator would produce right now. Plain invocation
writes it. Both read hs-game-sdk only - no game process, no network.
"""
import argparse
import sys
from pathlib import Path

TOOLS_DIR = Path(__file__).resolve().parent
FORGEPACT_DIR = TOOLS_DIR.parent
REPO_ROOT = FORGEPACT_DIR.parent
SDK_PY_PATH = REPO_ROOT / "hs-game-sdk" / "python"
OUTPUT_PATH = FORGEPACT_DIR / "plugin" / "include" / "ForgePact" / "SkillTimerNames.hpp"

if str(SDK_PY_PATH) not in sys.path:
    sys.path.insert(0, str(SDK_PY_PATH))

from hs_game_sdk import GameObject, get_ancestor_indices  # noqa: E402

# The 24 player-class name prefixes this convention covers (context: "The
# generated name table"). Order here is display order only; output is sorted
# by key.
CLASS_PREFIXES = (
    "Amazon", "Bard", "Butcher", "Demon_Slayer", "Demonspawn", "Exo", "Illusionist",
    "Jotunn", "Marauder", "Marksman", "Necromancer", "Nomad", "Paladin", "Pirate",
    "Plague_Doctor", "Prophet", "Pyromancer", "Redneck", "Samurai", "Shaman",
    "Shield_Lancer", "Stormweaver", "Viking", "White_Mage",
)

COMPANION_ANCESTOR = "Player_Sentry_Parent_obj"


def key_for(object_name: str):
    """The generated key for a class-prefixed object name, or None."""
    for prefix in CLASS_PREFIXES:
        head = prefix + "_"
        if object_name.startswith(head) and object_name.endswith("_obj"):
            middle = object_name[len(head):-len("_obj")]
            key = middle.replace("_", "").lower()
            if key:
                return key
    return None


def is_companion(member: GameObject) -> bool:
    for ancestor in get_ancestor_indices(member.value):
        if GameObject(ancestor).name == COMPANION_ANCESTOR:
            return True
    return False


def build_table():
    """Returns (rows, ambiguous): rows is the final sorted [(key, member)]
    list this generator ships, and ambiguous is {key: [members]} for the
    keys it drops because more than one non-companion object shares them."""
    candidates: dict[str, list] = {}
    for member in GameObject:
        key = key_for(member.name)
        if key is None:
            continue
        if is_companion(member):
            continue
        candidates.setdefault(key, []).append(member)

    rows = []
    ambiguous = {}
    for key, members in candidates.items():
        if len(members) > 1:
            ambiguous[key] = members
            continue
        rows.append((key, members[0]))
    rows.sort(key=lambda kv: kv[0])
    return rows, ambiguous


def render(rows) -> str:
    lines = [
        "#pragma once",
        "",
        "// GENERATED by tools/gen_skill_timer_names.py - do not hand-edit.",
        "// Regenerate with `py -3 tools/gen_skill_timer_names.py`; `--check` verifies",
        "// this file matches hs-game-sdk without writing anything.",
        "//",
        "// Issue #55 (D-S4): one entry per class-prefixed hs-game-sdk object that is",
        "// not a companion (no Player_Sentry_Parent_obj in its ancestor chain) and",
        "// whose generated key is not shared with another such object (ambiguous keys",
        "// are dropped, never guessed at). Key = the object's own name with its class",
        "// prefix and trailing _obj stripped, underscores removed, lower-cased",
        "// (White_Mage_Healing_Zone_obj -> healingzone). SkillTimerMod.hpp's rule",
        "// walk compares a talent's own abilityId, lower-cased, against this table's",
        "// key - never a hand-typed object name (AGENTS.md, \"Never Call an Address",
        "// You Resolved by Hand\").",
        "",
        '#include "SkillTimerMod.hpp"',
        "",
        "namespace ForgePact {",
        "",
        "inline constexpr SkillTimerNameEntry kSkillTimerNames[] = {",
    ]
    for key, member in rows:
        lines.append(f'    {{ "{key}", HeroSiege::Objects::GameObject::{member.name} }},')
    lines += [
        "};",
        "inline constexpr int kSkillTimerNameCount =",
        "    (int)(sizeof(kSkillTimerNames) / sizeof(kSkillTimerNames[0]));",
        "",
        "} // namespace ForgePact",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                         help="verify SkillTimerNames.hpp matches the generator; write nothing")
    args = parser.parse_args()

    rows, ambiguous = build_table()
    content = render(rows)

    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"SkillTimerNames.hpp: MISSING (generator would write {len(rows)} entries, "
                  f"{len(ambiguous)} ambiguous keys dropped)")
            return 1
        current = OUTPUT_PATH.read_bytes().decode("utf-8")
        if current != content:
            print(f"SkillTimerNames.hpp: STALE (regenerate; generator would write {len(rows)} entries, "
                  f"{len(ambiguous)} ambiguous keys dropped)")
            return 1
        print(f"SkillTimerNames.hpp: up to date ({len(rows)} entries)")
        return 0

    OUTPUT_PATH.write_bytes(content.encode("utf-8"))
    print(f"SkillTimerNames.hpp: wrote {len(rows)} entries ({len(ambiguous)} ambiguous keys dropped)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
