"""Embed the reviewed minimap sprites from assets/packmarks in the plugin.

Run with Python and Pillow after changing a final 16x16 RGBA PNG. Artwork is
kept as PNG source assets so rebuilding never redraws or regenerates the art.
The larger generated masters and their prompts are preserved beside the assets.

Writes PackMarkerIcons.hpp and build/packmark-icons/<kind>.png. The runtime
still writes defaults only if absent, preserving a player's custom images.
This script does not touch the game installation or reload live sprites.
"""
from __future__ import annotations

import io
from pathlib import Path

from PIL import Image

SIZE = 16
ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets" / "packmarks"
HEADER = ROOT / "plugin" / "include" / "ForgePact" / "PackMarkerIcons.hpp"
# Index order must match PackMarkers::Kind, rather than alphabetical order.
ICONS = ("normal", "ambush", "ancient", "champion", "colossal_chest", "legion", "miniboss")


def read_icon(name: str) -> bytes:
    path = ASSETS / f"{name}.png"
    data = path.read_bytes()
    with Image.open(io.BytesIO(data)) as image:
        image.load()
        if image.format != "PNG" or image.mode != "RGBA" or image.size != (SIZE, SIZE):
            raise ValueError(f"{path}: expected a {SIZE}x{SIZE} RGBA PNG")
        if image.getchannel("A").getextrema() != (0, 255):
            raise ValueError(f"{path}: expected transparent background and opaque artwork")
    return data


def main() -> int:
    # Validate the entire set before writing any generated output.
    icons = [(name, read_icon(name)) for name in ICONS]
    parts = ["// Generated by tools/make_packmark_icons.py - do not edit by hand.",
             "// Artwork: assets/packmarks (16x16 RGBA PNG, origin at the centre).",
             "// Order matches ForgePact::PackMarkers::Kind.",
             "#pragma once", "#include <cstddef>", "", "namespace ForgePact::PackMarkerIcons {",
             f"inline constexpr int kSize = {SIZE};",
             "struct Icon { const char* name; const unsigned char* data; size_t size; };"]
    for name, data in icons:
        parts.append(f"inline constexpr unsigned char k_{name}[] = {{")
        parts.extend("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ","
                     for i in range(0, len(data), 16))
        parts.append("};")
    parts.append("inline constexpr Icon kIcons[] = {")
    for name, _ in icons:
        parts.append(f'    {{ "{name}", k_{name}, sizeof(k_{name}) }},')
    parts.extend(["};", "inline constexpr size_t kIconCount = sizeof(kIcons) / sizeof(kIcons[0]);", "}"])
    HEADER.write_text("\n".join(parts) + "\n", encoding="utf-8")
    out_dir = ROOT / "build" / "packmark-icons"
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, data in icons:
        (out_dir / f"{name}.png").write_bytes(data)
    print(f"Embedded {len(icons)} reviewed sprites; preview files: {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
